### ISSUE TITLE
No Input Source after building

### ISSUE THREAD

**Issue by ProbablePrime** [partouf/OBSInfoWriter#50]
Hey, forgive me for making an issue that's more supportish in nature but i've been wracking my head for a few hours on this.

I've got this plugin building on windows and am looking to make some small changes and enhancements. But my built edition of the plugin doesn't result in an input source being available in OBS.

I've included a log file from OBS: [2022-06-19 03-04-38.txt](https://github.com/partouf/OBSInfoWriter/files/8935153/2022-06-19.03-04-38.txt)

That shows that its loaded, there are no errors etc... BUT no input.

Perhaps, you might be able to provide some diagnostic or debug steps here? I'm a little lost.

Thank you!

**Comment by partouf** [comment]
The relevant error is probably `03:04:39.558: obs_register_source: Tried to register obs_source_info with size 400 which is more than libobs currently supports (392)`, which I suspect means that the source that you're using to link against OBS is incompatible with your OBS version 27.2.4.

You will have to checkout this tag https://github.com/obsproject/obs-studio/releases/tag/27.2.4 and build with that in order to produce a compatible plugin.

**Comment by ProbablePrime** [comment]
Thank you so much for a pointer, I'll go ahead and try this. I really appreciate it!
